



FROM public.ecr.aws/lambda/python:3.12

COPY src/s3_lambda/app.py ${LAMBDA_TASK_ROOT}

COPY src/s3_lambda/requirements.txt
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["app.handler"]



